//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OfferWebSystem.EFnClass
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    public partial class OffersInfo
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public OffersInfo()
        {
            this.OfferAvailOutlets = new HashSet<OfferAvailOutlet>();
            this.OfferReviews = new HashSet<OfferReview>();
            this.OfferViews = new HashSet<OfferView>();
        }
    
        public long ID { get; set; }
        [Required(ErrorMessage = "Enter Post Title")]
        public string PostName { get; set; }
        public long OfferCat { get; set; }
        public long OfferLoc { get; set; }

        [Required(ErrorMessage = "Enter Start Date")]
        [DataType(DataType.Date)]
        public System.DateTime OfferStartDate { get; set; }

        [Required(ErrorMessage = "Enter End Date")]
        [DataType(DataType.Date)]
        public System.DateTime OfferEndDate { get; set; }

        [Required(ErrorMessage = "Enter Discount Tag")]
        public string OfferDiscountAmt { get; set; }
        public long OfferStatus { get; set; }
        [Required(ErrorMessage = "Enter Discount Details")]
        
        public string OfferDetails { get; set; }
        public string OfferImagePath { get; set; }
        public Nullable<long> OfferFeatureVal { get; set; }
        public bool IsActive { get; set; }
        public long CreatedBy { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public Nullable<long> ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedOn { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OfferAvailOutlet> OfferAvailOutlets { get; set; }
        public virtual OfferCategory OfferCategory { get; set; }
        public virtual OfferLocation OfferLocation { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OfferReview> OfferReviews { get; set; }
        public virtual SysEnum SysEnum { get; set; }
        public virtual SysEnum SysEnum1 { get; set; }
        public virtual SysUser SysUser { get; set; }
        public virtual SysUser SysUser1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OfferView> OfferViews { get; set; }
    }
}
